---
- include_role:
    name: terraplate

- name: Ensure the credentials file exists
  copy:
    dest: '{{ provision.tfvars.path }}/{{ provision.tfvars.file }}'
    force: no
    content: ''

- name: Copy the template to the module
  copy:
    src: templates
    dest: '{{ res_dir }}'

- include_role:
    name: terraplate
    tasks_from: render
